#services:
#  mysql:
#    image: mysql:8.0.33
#    ports:
#      - '3306:3306'
#    volumes:
#      - ./data:/var/lib/mysql # Персистентное хранилище
#    environment:
#      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
#      MYSQL_DATABASE: 'app'
#      MYSQL_USER: 'app'
#      MYSQL_PASSWORD: 'pass'
#    platform: linux/amd64  # Для совместимости на Apple Silicon

services:
  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    platform: linux/amd64