name: Java CI Test Runner

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Start Docker services
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo docker-compose up -d
          sleep 20

      - name: Start application
        run: |
          java -jar ./artifacts/aqa-shop.jar &
          sleep 15

      - name: Start payment simulator
        run: |
          cd gate-simulator && npm start &
          sleep 10

      - name: Run tests
        run: |
          chmod +x gradlew
          ./gradlew clean test -Dselenide.headless=true